baseURL = "/"
languageCode = "en-US"
title = "Geert Eltink"
googleAnalytics = "UA-56579105-2"
enableRobotsTxt = true
enableGitInfo = true
disqusShortname = "elt-ink"
copyright = "Geert Eltink"
rssLimit = 10
summarylength = 30
pygmentsCodeFences=true

[author]
    name = "Geert Eltink"

[imaging]
    resampleFilter = "Linear"
    quality = 80

[permalinks]
    blog = "/blog/:filename/"

[params]
    description = "It all starts with an idea, I can make yours a reality."
