version: "2"
services:

  datastore:
    image: busybox
    container_name: ${PROJECT_ID}-datastore
    volumes:
      - .:/app

  web:
    image: xtreamwayz/nginx
    container_name: ${PROJECT_ID}-web
    ports:
      - "80:80"
    volumes_from:
      - datastore
    links:
      - php

  php:
    image: xtreamwayz/php:latest
    #image: xtreamwayz/php:5.6
    container_name: ${PROJECT_ID}-php
    volumes_from:
      - datastore
    links:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: ${PROJECT_ID}-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
