version: "2"
services:

  web:
    image: xtreamwayz/nginx
    container_name: ${PROJECT_ID}-web
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}:/app
    links:
      - php

  php:
    image: xtreamwayz/php:latest
    container_name: ${PROJECT_ID}-php
    volumes:
      - ${PROJECT_ROOT}:/app
    links:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: ${PROJECT_ID}-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
