name: continuous-integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint:astro
      - run: npm run lint:types
      - run: npm run lint:imports
      - run: npm run lint:ox
      - run: npm run lint:es
      - run: npm run lint:md
      - run: npm run lint:css
      - run: npm run lint:prettier
